"""Vote Table

Revision ID: 3845c71578ab
Revises: 
Create Date: 2021-08-03 11:22:33.141931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3845c71578ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote',
    sa.Column('vote_id', sa.Integer(), nullable=False),
    sa.Column('candidates', sa.Text(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('vote_id')
    )
    op.create_index(op.f('ix_vote_datetime'), 'vote', ['datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vote_datetime'), table_name='vote')
    op.drop_table('vote')
    # ### end Alembic commands ###
